get http://localhost:3000/todos/?status=TO%20DO

get http://localhost:3000/todos/7


get http://localhost:3000/agenda/?date=2021-02-2



post http://localhost:3000/todos/
Content-Type : application/json
{
 "id": 8,
 "todo": "Learn css",
 "priority": "LOW",
 "status": "TO DO",
 "category": "LEARNING",
 "dueDate": "2021-02-22"
}


put http://localhost:3000/todos/7/
Content-Type : application/json
{ "dueDate": "2021-02-2" }

delete http://localhost:3000/todos/7/